## Usage
#
# create .git/hooks/pre-commit:
#   pre-commit install
#
# or create .git/hooks/pre-push:
#   pre-commit install --hook-type pre-push
#
# test all files:
#   pre-commit run --all-files
#
# uninstall hooks:
#   pre-commit uninstall

fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff
        args: ["check"]
        types: [python]
        language: system
      - id: ruff-format
        name: ruff format
        entry: ruff
        args: ["format", "--check"]
        types: [python]
        language: system
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        args: ["-c", "pyproject.toml"]
        types: [python]
        language: system
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        types: [python]
        language: system
        pass_filenames: false
