services:
  edp:
    image: edp
    build: .
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "10"
    #       memory: "20G"
    # security_opt:
    #   - no-new-privileges:true
    #   - seccomp=default.json
    # read_only: true
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
    volumes:
      - edp_work:/work
    ports:
      - "8000:8000"

volumes:
  edp_work:
