[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "edp"
version = "0.2.0"
authors = [
    { name = "Michael Wielpuetz", email = "mw@beebucket.de" },
    { name = "Daniel Eckstein", email = "de@beebucket.de" },
    { name = "Joshua Lauterbach", email = "jl@beebucket.de" },
]
description = "Beebucket application to create Enhanced Dataset Profiles."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "argparse",
    "filetype",
    "fitter",
    "matplotlib",
    "numpy",
    "pandas",
    "pathlib",
    "pydantic",
    "boto3",
    "requests"
]

[project.scripts]
export_edps_schema = "edp.types:export_edp_schema"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
    "bandit",
    "black",
    "isort",
    "mypy",
    "pandas-stubs",
    "scipy-stubs",
    "boto3-stubs[full]",
    "types-requests"
]
dev = ["edp[test]"]

[tool.setuptools.packages.find]
where = ["."]
include = ["edp*"]
exclude = ["test*"]

[tool.isort]
profile = 'black'
skip = ['.conda']
skip_gitignore = true

[tool.black]
line-length = 120

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
addopts = "-W error"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

[tool.bandit]
exclude_dirs = ['tests']
skips = ["B403"]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
exclude = ["build"]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["filetype", "fitter"]
ignore_missing_imports = true
