name: Release

on:
    push:
        tags: "*"

env:
    EDPS_SCHEMA: edps_schema_${{ github.ref_name }}.json

jobs:
    generate_schemas:
        runs-on: ubuntu-24.04
        name: Generate Schemas
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   uses: actions/setup-python@v5
            with:
                python-version: 3.12
                cache: 'pip'
        -   name: Install Application
            run: pip install .
        -   name: Generate Schema
            run: export_edps_schema --output ${{ env.EDPS_SCHEMA }}
        -   uses: actions/upload-artifact@v4
            with:
                name: ${{ env.EDPS_SCHEMA }}
                path: ${{ env.EDPS_SCHEMA }}
        
    create_release:
        runs-on: ubuntu-24.04
        name: Create Release
        needs:
        -   generate_schemas
        env:
            EDPS_SCHEMA: edps_schema_${{ github.ref_name }}.json
        steps:
        -   uses: actions/download-artifact@v4
            with:
                name: ${{ env.EDPS_SCHEMA }}
                path: ${{ env.EDPS_SCHEMA }}
        -   name: Release
            uses: softprops/action-gh-release@v2
            with:
                files: |
                    ${{ env.EDPS_SCHEMA }}
                fail_on_unmatched_files: true
                draft: true
                generate_release_notes: true
