name: Release

on:
    push:
        tags: "*"

env:
    EDPS_SCHEMA: edps_schema_${{ github.ref_name }}.json
    OPENAPI_SCHEMA: edps_openapi_${{ github.ref_name }}.json
    IMAGE_PATH: beebucket/edps
    WHEEL_NAME: edps.whl
    LICENSES_ARTIFACT_NAME: licenses.csv

jobs:
    build_wheel:
        runs-on: ubuntu-24.04
        name: Build Release Wheel
        env:
            DISTRIBUTION_DIR: "${{ github.workspace }}/dist"
            VERSION: "${{ github.ref_name }}"
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   uses: actions/setup-python@v5
            with:
                python-version-file: '.python-version'
                cache: 'pip'
        -   name: Build Wheel
            run: /bin/bash ${{ github.workspace}}/scripts/build_wheel.sh
        -   uses: actions/upload-artifact@v4
            with:
                name: ${{ env.WHEEL_NAME }}
                path: "${{ env.DISTRIBUTION_DIR }}/edps*.whl"
                if-no-files-found: error

    generate_schemas:
        runs-on: ubuntu-24.04
        name: Generate Schemas
        needs:
        -   build_wheel
        steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-python@v5
            with:
                python-version-file: '.python-version'
                cache: 'pip'
        -   uses: actions/download-artifact@v4
            id: download_wheel
            with:
                name: ${{ env.WHEEL_NAME }}
                path: ${{ github.workspace }}
        -   name: Install
            run: pip install ${{ steps.download_wheel.outputs.download-path }}
        -   name: Generate EDPS Schema
            run: export_edps_schema --output ${{ env.EDPS_SCHEMA }}
        -   uses: actions/upload-artifact@v4
            with:
                name: ${{ env.EDPS_SCHEMA }}
                path: ${{ env.EDPS_SCHEMA }}
        -   name: Generate OpenAPI Schema
            run: export_openapi_schema --output ${{ env.OPENAPI_SCHEMA }}
        -   uses: actions/upload-artifact@v4
            with:
                name: ${{ env.OPENAPI_SCHEMA }}
                path: ${{ env.OPENAPI_SCHEMA }}

    license_report:
        runs-on: ubuntu-24.04
        name: Create License Report
        needs:
        -   build_wheel
        steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-python@v5
            with:
                python-version-file: '.python-version'
                cache: 'pip'
        -   uses: actions/download-artifact@v4
            id: download_wheel
            with:
                name: ${{ env.WHEEL_NAME }}
                path: ${{ github.workspace }}
        -   name: Install
            run: pip install ${{ steps.download_wheel.outputs.download-path }}[test]
        -   name: Run pip-licenses
            run: pip-licenses --format=csv --with-url --with-authors --order=license --output-file ${{ env.LICENSES_ARTIFACT_NAME }}
        -   name: Upload License Report
            uses: actions/upload-artifact@v4
            with:
                name: ${{ env.LICENSES_ARTIFACT_NAME }}
                path: ${{ env.LICENSES_ARTIFACT_NAME }}

    build_and_release_docker:
        runs-on: ubuntu-24.04
        name: Build and Push EDPS docker image
        needs:
        -   build_wheel
        timeout-minutes: 1440
        env:
            REGISTRY: docker.io
        outputs:
            dockerhub_reference: "${{ steps.meta.outputs.tags }}"
        steps:
        -   uses: docker/login-action@v3
            with:
                registry: ${{ env.REGISTRY }}
                username: cicdcorebeebucket
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        -   uses: actions/checkout@v4
        -   uses: actions/download-artifact@v4
            id: download_wheel
            with:
                name: ${{ env.WHEEL_NAME }}
                path: ${{ github.workspace }}/dist
        -   uses: docker/setup-qemu-action@v3
        -   uses: docker/setup-buildx-action@v3
        -   name: Extract Docker metadata
            id: meta
            uses: docker/metadata-action@v5.5.1
            with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}
                flavor: latest=false
                tags: |
                    type=ref,event=branch
                    type=ref,event=tag
                    type=ref,event=pr
                    type=semver,pattern={{version}}
        -   name: Build and push Docker image
            id: build-and-push
            uses: docker/build-push-action@v6
            with:
                context: .
                file: docker/Dockerfile
                platforms: |
                    linux/arm64,
                    linux/amd64
                build-args: |
                    VERSION=${{ github.ref_name }}
                push: True
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

    create_release:
        runs-on: ubuntu-24.04
        name: Create Release
        needs:
        -   build_wheel
        -   generate_schemas
        -   build_and_release_docker
        -   license_report
        env:
            ARTIFACTS_DIR: ${{ github.workspace }}/release_artifacts
        steps:
        -   name: Create Directory for artifacts
            run: mkdir -p ${{ env.ARTIFACTS_DIR }}
        -   uses: actions/download-artifact@v4
            with:
                name: ${{ env.EDPS_SCHEMA }}
                path: ${{ env.ARTIFACTS_DIR }}
        -   uses: actions/download-artifact@v4
            with:
                name: ${{ env.WHEEL_NAME }}
                path: ${{ env.ARTIFACTS_DIR }}
        -   uses: actions/download-artifact@v4
            with:
                name: ${{ env.OPENAPI_SCHEMA }}
                path: ${{ env.ARTIFACTS_DIR }}
        -   uses: actions/download-artifact@v4
            with:
                name: ${{ env.LICENSES_ARTIFACT_NAME }}
                path: ${{ env.ARTIFACTS_DIR }}
        -   name: Release
            uses: softprops/action-gh-release@v2
            with:
                body:
                    "Dockerhub Reference (private): ${{ needs.build_and_release_docker.outputs.dockerhub_reference }}\n"
                files: ${{ env.ARTIFACTS_DIR }}/*
                fail_on_unmatched_files: true
                draft: true
                generate_release_notes: true
