name: Build container

on: [pull_request]

jobs:
    linter:
        runs-on: ubuntu-24.04
        name: Linters
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   uses: actions/setup-python@v5
            with:
                python-version-file: '.python-version'
                cache: "pip"
        -   name: Install
            run: |
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com/".insteadOf "git@github.com:"
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com".insteadOf "https://github.com"
                pip install .[test]
        -   name: mypy
            run: mypy .
        -   name: ruff check
            run: ruff check --output-format=github .
        -   name: run format
            run: ruff format --check .
        -   name: check licenses
            run: pip-licenses
    unit-tests:
        runs-on: ubuntu-24.04
        name: Perform unit tests
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   uses: actions/setup-python@v5
            with:
                python-version-file: '.python-version'
                cache: "pip"
        -   name: Install
            run: |
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com/".insteadOf "git@github.com:"
                git config --global url."https://${{ secrets.GIT_HUB_API_KEY }}@github.com".insteadOf "https://github.com"
                pip install .[test]
        -   name: Execute tests
            run: |
                pytest .
