name: Build container

on: [pull_request]

env:
    PYTHON_VERSION: 3.12

jobs:
    linter:
        runs-on: ubuntu-24.04
        name: Linters
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   uses: actions/setup-python@v5
            with:
                python-version: ${{ env.PYTHON_VERSION }}
                cache: "pip"
        -   name: Install
            run: |
                pip install .[test]
        -   name: Execute tests
            run: |
                mypy .
                black --check .
                isort --check .
                bandit --configfile pyproject.toml -r .

    unit-tests:
        runs-on: ubuntu-24.04
        name: Perform unit tests
        steps:
        -   uses: actions/checkout@v4
            with:
                lfs: true
        -   uses: actions/setup-python@v5
            with:
                python-version: ${{ env.PYTHON_VERSION }}
                cache: "pip"
        -   name: Install
            run: |
                pip install .[test]
        -   name: Execute tests
            run: |
                pytest .