name: Lint and Test

on: [pull_request]

jobs:
    lint-and-unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: beebucket/lint-and-test-action@v1
              with:
                token: ${{ secrets.GIT_HUB_API_KEY }}
