name: Lint and Test

on: [pull_request]

jobs:
  lint-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: beebucket/lint-and-test-action@v1
        with:
          install-token: ${{ secrets.GIT_HUB_API_KEY }}
